//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Joy.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IJoyListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
public partial class JoyBaseListener : IJoyListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.cycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCycle([NotNull] JoyParser.CycleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.cycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCycle([NotNull] JoyParser.CycleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.simpleDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleDefinition([NotNull] JoyParser.SimpleDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.simpleDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleDefinition([NotNull] JoyParser.SimpleDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] JoyParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] JoyParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] JoyParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] JoyParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.setLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetLiteral([NotNull] JoyParser.SetLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.setLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetLiteral([NotNull] JoyParser.SetLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.quotationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuotationLiteral([NotNull] JoyParser.QuotationLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.quotationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuotationLiteral([NotNull] JoyParser.QuotationLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.atomicSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicSymbol([NotNull] JoyParser.AtomicSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.atomicSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicSymbol([NotNull] JoyParser.AtomicSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.booleanConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanConstant([NotNull] JoyParser.BooleanConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.booleanConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanConstant([NotNull] JoyParser.BooleanConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.integerConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerConstant([NotNull] JoyParser.IntegerConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.integerConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerConstant([NotNull] JoyParser.IntegerConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.floatConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatConstant([NotNull] JoyParser.FloatConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.floatConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatConstant([NotNull] JoyParser.FloatConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.characterConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharacterConstant([NotNull] JoyParser.CharacterConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.characterConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharacterConstant([NotNull] JoyParser.CharacterConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.stringConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringConstant([NotNull] JoyParser.StringConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.stringConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringConstant([NotNull] JoyParser.StringConstantContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
