//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Joy.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JoyParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
public interface IJoyListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.cycle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCycle([NotNull] JoyParser.CycleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.cycle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCycle([NotNull] JoyParser.CycleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.simpleDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleDefinition([NotNull] JoyParser.SimpleDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.simpleDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleDefinition([NotNull] JoyParser.SimpleDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] JoyParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] JoyParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] JoyParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] JoyParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.setLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetLiteral([NotNull] JoyParser.SetLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.setLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetLiteral([NotNull] JoyParser.SetLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.quotationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuotationLiteral([NotNull] JoyParser.QuotationLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.quotationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuotationLiteral([NotNull] JoyParser.QuotationLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.atomicSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicSymbol([NotNull] JoyParser.AtomicSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.atomicSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicSymbol([NotNull] JoyParser.AtomicSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.booleanConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanConstant([NotNull] JoyParser.BooleanConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.booleanConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanConstant([NotNull] JoyParser.BooleanConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.integerConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerConstant([NotNull] JoyParser.IntegerConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.integerConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerConstant([NotNull] JoyParser.IntegerConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.floatConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatConstant([NotNull] JoyParser.FloatConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.floatConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatConstant([NotNull] JoyParser.FloatConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.characterConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacterConstant([NotNull] JoyParser.CharacterConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.characterConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacterConstant([NotNull] JoyParser.CharacterConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JoyParser.stringConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringConstant([NotNull] JoyParser.StringConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JoyParser.stringConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringConstant([NotNull] JoyParser.StringConstantContext context);
}
