//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Xil.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IXilListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
public partial class XilBaseListener : IXilListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.cycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCycle([NotNull] XilParser.CycleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.cycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCycle([NotNull] XilParser.CycleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.simpleDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleDefinition([NotNull] XilParser.SimpleDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.simpleDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleDefinition([NotNull] XilParser.SimpleDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] XilParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] XilParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] XilParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] XilParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.setLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetLiteral([NotNull] XilParser.SetLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.setLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetLiteral([NotNull] XilParser.SetLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.quotationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuotationLiteral([NotNull] XilParser.QuotationLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.quotationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuotationLiteral([NotNull] XilParser.QuotationLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.atomicSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicSymbol([NotNull] XilParser.AtomicSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.atomicSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicSymbol([NotNull] XilParser.AtomicSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.booleanConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanConstant([NotNull] XilParser.BooleanConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.booleanConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanConstant([NotNull] XilParser.BooleanConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.integerConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerConstant([NotNull] XilParser.IntegerConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.integerConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerConstant([NotNull] XilParser.IntegerConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.floatConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatConstant([NotNull] XilParser.FloatConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.floatConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatConstant([NotNull] XilParser.FloatConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.characterConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharacterConstant([NotNull] XilParser.CharacterConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.characterConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharacterConstant([NotNull] XilParser.CharacterConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.stringConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringConstant([NotNull] XilParser.StringConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.stringConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringConstant([NotNull] XilParser.StringConstantContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
