//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Xil.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="XilParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
public interface IXilListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.cycle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCycle([NotNull] XilParser.CycleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.cycle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCycle([NotNull] XilParser.CycleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.simpleDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleDefinition([NotNull] XilParser.SimpleDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.simpleDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleDefinition([NotNull] XilParser.SimpleDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] XilParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] XilParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] XilParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] XilParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.setLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetLiteral([NotNull] XilParser.SetLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.setLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetLiteral([NotNull] XilParser.SetLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.quotationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuotationLiteral([NotNull] XilParser.QuotationLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.quotationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuotationLiteral([NotNull] XilParser.QuotationLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.atomicSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicSymbol([NotNull] XilParser.AtomicSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.atomicSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicSymbol([NotNull] XilParser.AtomicSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.booleanConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanConstant([NotNull] XilParser.BooleanConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.booleanConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanConstant([NotNull] XilParser.BooleanConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.integerConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerConstant([NotNull] XilParser.IntegerConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.integerConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerConstant([NotNull] XilParser.IntegerConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.floatConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatConstant([NotNull] XilParser.FloatConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.floatConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatConstant([NotNull] XilParser.FloatConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.characterConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacterConstant([NotNull] XilParser.CharacterConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.characterConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacterConstant([NotNull] XilParser.CharacterConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XilParser.stringConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringConstant([NotNull] XilParser.StringConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XilParser.stringConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringConstant([NotNull] XilParser.StringConstantContext context);
}
