//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Xil.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="XilParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
public interface IXilVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.cycle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCycle([NotNull] XilParser.CycleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.simpleDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleDefinition([NotNull] XilParser.SimpleDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] XilParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] XilParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.setLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetLiteral([NotNull] XilParser.SetLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.quotationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuotationLiteral([NotNull] XilParser.QuotationLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.atomicSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomicSymbol([NotNull] XilParser.AtomicSymbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.booleanConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanConstant([NotNull] XilParser.BooleanConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.integerConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerConstant([NotNull] XilParser.IntegerConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.floatConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatConstant([NotNull] XilParser.FloatConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.characterConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacterConstant([NotNull] XilParser.CharacterConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XilParser.stringConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringConstant([NotNull] XilParser.StringConstantContext context);
}
